const data = {
    avatar_url: "https://avatars0.githubusercontent.com/u/19576746?v=4",
    bio: null,
    blog: "",
    company: null,
    created_at: "2016-05-25T18:00:04Z",
    email: null,
    events_url: "https://api.github.com/users/LuckyMcBeast/events{/privacy}",
    followers: 3,
    followers_url: "https://api.github.com/users/LuckyMcBeast/followers",
    following: 12,
    following_url: "https://api.github.com/users/LuckyMcBeast/following{/other_user}",
    gists_url: "https://api.github.com/users/LuckyMcBeast/gists{/gist_id}",
    gravatar_id: "",
    hireable: null,
    html_url: "https://github.com/LuckyMcBeast",
    id: 19576746,
    location: "Atlanta, GA",
    login: "LuckyMcBeast",
    name: "M. Cullen McClellan",
    node_id: "MDQ6VXNlcjE5NTc2NzQ2",
    organizations_url: "https://api.github.com/users/LuckyMcBeast/orgs",
    public_gists: 0,
    public_repos: 38,
    received_events_url: "https://api.github.com/users/LuckyMcBeast/received_events",
    repos_url: "https://api.github.com/users/LuckyMcBeast/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/LuckyMcBeast/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/LuckyMcBeast/subscriptions",
    twitter_username: null,
    type: "User",
    updated_at: "2020-11-18T00:56:33Z",
    url: "https://api.github.com/users/LuckyMcBeast"
}